# Judo Generator Commons

JUDO Generator Commons project contains helpers, annotations and maven utils which can be used on a generator engine development

This is a general representation of the generator, which will be parameterized using one of the meta-models.
We use the generator in these meta models:

- judo-meta-esm
- judo-meta-pam
- judo-meta-ui

There are 3 modules in these projects, which are related to the generator commons:

- generator-engine
- generator-maven-project
- generator-maven-plugin-test

The `generator-engine` teaches the generator commons how to release the items. This bind the meta model to the generator.
Models are transformed into template parameters in this project.


For example in the judo-meta-esm :

    EsmGenerator.java -> Process of parameterization.

    EsmGeneratorParameter.java -> This contains the model as a parameter, the generatorContext, the DirectoryResolvers etc.

=== Description of a project

The <project type>.yaml file describes what template is used for that and control which parameters are passed and the model can control HOW the templates can be used.
Each generator-engine project has test directory with test project. This test project provides an example of how a `test-project.yaml` description looks like.

Typically struct is :

[source,yaml]
----
templates:

  - name: testOverride
    pathExpression: "#actorType.name + '/actorToOverride'"
    templateName: test1/actorToOverride.hbs
    actorTypeBased: true

  - name: testReplace
    pathExpression: "#actorType.name + '/actorToReplace'"
    templateName: test1/actorToReplace.hbs
    actorTypeBased: true

  - name: testDelete
    pathExpression: "#actorType.name + '/actorToDelete'"
    templateName: test1/actorToDelete.hbs
    actorTypeBased: true
----

* `templates`: This defines a list of templates.

* `name`: This is like an id for the template. Based on this, we can override the template later.

* `pathExpression`: This specifies where the generated file is located and under what name it will be generated.

===== Expressions

We use spring expression language (https://docs.spring.io/spring-framework/docs/3.0.x/reference/expressions.html[springEL]), because handlebars only support string output. Every expression in yaml is SpringEL.

For example : templateName, actoryExpression, condtionExpresison and templateContext use it.

* `templateName`: The location of the handlebars file relative to the template root.

* `actorTypeBased`: When actorTypeBased template used, the template called for all actor types and the actorType variable is defined.
    ** We can override the name of the property.
    +
    For example we can override in https://github.com/BlackBeltTechnology/judo-meta-ui/blob/develop/generator-engine/src/main/java/hu/blackbelt/judo/meta/ui/generator/engine/UiGeneratorTemplateMixin.java[this] way.
    We use this class for the generationContext builder.

[source,java]
----
//if the actorTypeBased is true, we need to defined in the EsmGeneratorParameter

    @Builder.Default
    Predicate<ActorType> actorTypePredicate = a -> true;

    @NonNull
    Function<ActorType, File> actorTypeTargetDirectoryResolver;

----

Not in the example :

* `factoryExpression`: Factory expression is used to create files. It returns a list of objects which are used as root context for the given handlebar template.

* `condtionExpresison`: With the help of the ConditionExpression, we can exclude cases that we do not want to generate if the condition is false. This should return a Boolean Spring expression.

* `templateContext`: Template context is used to put expression result to template variable. We can refer to the expression through the template context name. (Not used often because of the helpers).
** Example:
+
We can refer to self through the applicationAsVariable template context name.
+
[source,yaml]
----
    templateContext:
        - name: applicationAsVariable
          expression: "#self"
----


* `copy`: It can be used to copy a binary file. In this case the template file used as binary, no templating is performed.

* `permission`: It can be used to add execution permission to files. For example bash files.

** We use the POSIX permission pattern. Use this pattern `rwxrwxrwx` (read,write,execute).
    This contains 3 permission type in this order:
*** owner
*** group
*** other

** We add the global permission first if it is present and if the template have a local permission we use that.

** Example

+
[source,yaml]
----
  - name: judo.sh
    pathExpression: "'judo.sh'"
    templateName: judo.sh.hbs
    permission: rwxrwx---
    actorTypeBased: false
----

* `exclude`: This parameter can be used in an override to exclude the given template from a generation. With this parameter only the `name` is effective.

=== GeneratorModel

The `GeneratorModel` Java class loads the Handlebars files from the base directory and overrides them with the files from the override directory if it is necessary.
The class contains a global permission parameter that adds a global permission to all of the Handlebars files.
(The `GeneratorTemplate` Java class, contained within the GeneratorModel class, includes all of the YAML representations listed earlier. The GeneratorModel maps the YAML properties to the GeneratorTemplate.)

=== Generator Maven Project

https://github.com/BlackBeltTechnology/judo-meta-esm/tree/develop/generator-maven-plugin#readme[This] link contains the description of the generator maven plugin.

=== Helper registration

We don't register helpers manually. To register a java helper class use the `@TemplateHelper` annotation.

IMPORTANT: The Java class methods must be static.

If you inherit your helper class from the `StaticMethodValueResolver` class, you can refer to its methods using dot notation.

The helpers are available in springEL too with # prefix.

=== Self meaning in different situations

The self mean different thinks in the springEL and Handlebars depend on the YAML properties:

- If actorTypeBased is enabled, then #self refers to the actor.

- If we have a `factoryExpression`, then the self is the current iterated element of collection.

- If we don't have a `factoryExpression` and it is not actorTypeBased, then #self refers to the model.

=== How to reach templateParameters

They are not static and have to be accessible to static helper methods which are called from parallel processes. This can cause issues with parallel building. To void
this issue the `@ContextAccessor` annotation and a `bindContext` method.

Example:
[source,java]
----
@TemplateHelper
@ContextAccessor
public class StoredVariableHelper extends StaticMethodValueResolver {

    public static void bindContext(Map<String, ?> context) {
        ThreadLocalContextHolder.bindContext(context);
    }

    public static synchronized String getApiPrefixLocal(Object object) {
        return (String) ThreadLocalContextHolder.getVariable("apiPrefix");
    }

    public static synchronized Boolean isGenerateOptionalTypes(Object object) {
        return Boolean.parseBoolean((String) ThreadLocalContextHolder.getVariable("generateOptionalTypes"));
    }

    public static synchronized Boolean isGeneratePayloadValidator(Object object) {
        return Boolean.parseBoolean((String) ThreadLocalContextHolder.getVariable("generatePayloadValidator"));
    }
}

----

This only need if we used the templateParameters in a java Helper.

=== Checksum generation
A checksum is a value calculated from data to detect errors during transmission or storage. It ensures data integrity and any mismatches indicate errors in the data.

* The checksum generation is a goal of the generator-maven-plugin.

Example:

[source,xml]
----
                    <execution>
                        <id>execute-ui-checksum-from-file</id>
                        <phase>generate-test-resources</phase>
                        <goals>
                            <goal>checksum</goal>
                        </goals>
                        <configuration>
                            <ui>${basedir}/src/test/resources/MultiPrincipalTest-ui.model</ui>
                            <destination>${basedir}/target/test-classes/ui/file</destination>
                        </configuration>
                    </execution>
----
* The [modelName]ProjectGenerateMojo is responsible for generating the files, while the [modelName]ProjectCalculateChecksumMojo is responsible for generating checksums for the files.

* The .generated-files-[actor]-[actor] contains the actorTypeBased checksums. The .generated-files contains the not actorTypeBased checksums

** A line contains a file name and a md5sum value.

=== Generator ignore file

IMPORTANT: Sometimes a developer needs to replace generated file with custom developed file. On that case the generator has to ignore the given file to keep the edited version. To achieve this `.generator-ignore` file can be used. In this case, every unexpected behavior is the responsibility of the developer.

We use GLOB format, so the usage is same as .gitignore.

Here is some example :

* Ignore files with a specific extension: *.log, *.txt, *.docx

* Ignore a specific file: config.ini, secrets.txt

* Ignore a specific directory: node_modules/

* Ignore all files in a directory except a specific file: docs/* (ignores all files in the docs directory), !docs/index.md (except for the index.md file in the docs directory)

* Ignore files based on a pattern: *_backup (ignores all files with "_backup" in their name)

* Ignore files based on their path: /bin/ (ignores the bin directory at the root of the project)

* Ignore all .md files in the docs directory and its subdirectories: docs/\**/*.md

* Ignore .init files in the src directory: src/*.init

How it works now:

* When index file is not present in the generation process, the system works like now, overwriting target files, additionally creating the index.

* When a file is present in the generator ignore list during the index or new generation process, the index will still contain it but the file will be ignored in the checks and writing.

* If a generated file have been modified by hand - the current checksum does not match with the last generation’s checksum, the system have to terminate with error “Generated file have been modified, please revert or delete it or add to generator-ignore”. When a file not presented in the index, it will be written and overwrite the existing files.

* When a file presented on the stored index and the new generation does not contain it, have to be deleted.

* When the new generation’s checksum * match with the current file’s checksum, do not touch it. It will help for compiler’s for incremental building.
